export const DEFAULT_OPENAPI_METHOD = 'POST'
export const DEFAULT_OPENAPI_SUCCESS_DESCRIPTION = 'OK'
export const DEFAULT_OPENAPI_INPUT_STRUCTURE = 'compact'
export const DEFAULT_OPENAPI_OUTPUT_STRUCTURE = 'compact'
