import type { JsonSchemaKeywords } from './types'

export const JSON_SCHEMA_LOGIC_KEYWORDS = new Set<JsonSchemaKeywords | string & {}>([
  '$dynamicRef',
  '$ref',
  'additionalItems',
  'additionalProperties',
  'allOf',
  'anyOf',
  'const',
  'contains',
  'contentEncoding',
  'contentMediaType',
  'contentSchema',
  'dependencies',
  'dependentRequired',
  'dependentSchemas',
  'else',
  'enum',
  'exclusiveMaximum',
  'exclusiveMinimum',
  'format',
  'if',
  'items',
  'maxContains',
  'maximum',
  'maxItems',
  'maxLength',
  'maxProperties',
  'minContains',
  'minimum',
  'minItems',
  'minLength',
  'minProperties',
  'multipleOf',
  'not',
  'oneOf',
  'pattern',
  'patternProperties',
  'prefixItems',
  'properties',
  'propertyNames',
  'required',
  'then',
  'type',
  'unevaluatedItems',
  'unevaluatedProperties',
  'uniqueItems',
])

export const JSON_SCHEMA_PRIMITIVE_TYPES = new Set<string>(['string', 'number', 'integer', 'boolean', 'null'])

export const JSON_SCHEMA_RECORD_KEYWORDS = new Set(['properties', 'patternProperties', 'dependentSchemas', 'dependencies', '$defs'])
