[test]
coverageReporter = [
  "text",
  "lcov"
]
coveragePathIgnorePatterns = [
  # Exclude other packages to prevent overlap in the final merged coverage report.
  "../**",
  "**/*.test.*",
  "**/tests/**",
]
